resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/mlizza/concourse-poc.git
      branch: main
    webhook_token: abcd
    check_every: never
    icon: github

jobs:
  - name: concourse-poc-job
    plan:
      # Add a get step referencing the resource
      - get: repo
        trigger: true   # tell Concourse to trigger this job when new versions are emitted
      - task: concourse-poc-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: "golang:1.16"
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - -cx
              - |
                cd repo
                make build