resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/mlizza/concourse-poc.git
      branch: main
    webhook_token: abcd
    check_every: never
    icon: github
  - name: go-builder
    type: registry-image
    source:
      repository: golang
      tag: 1.16

jobs:
  - name: concourse-poc-job
    plan:
      # Add a get step referencing the resource
      - get: repo
        trigger: true   # tell Concourse to trigger this job when new versions are emitted
      - load_var: version
        file: repo/VERSION
      - task: concourse-poc-task
        image: go-builder
        params:
          VERSION: ((.:version))
        file: repo/ci/tasks/go-build.yml
      - task: concourse-poc-task
        image: go-builder
        params:
          VERSION: ((.:version))
        file: repo/ci/tasks/go-test.yml
