resources:
  # Repo Github
  - name: repo
    type: git
    source:
      uri: https://github.com/mlizza/concourse-poc.git
      branch: main
      username: ((mlizza/username))
      password: ((mlizza/password))
    webhook_token: abcd
    check_every: never
    icon: github
  # Builder
  - name: go-builder
    icon: docker
    type: registry-image
    source:
      repository: golang
      tag: 1.16
  # Semver
  - name: version-bumper
    type: semver
    source:
      driver: git
      uri: https://github.com/mlizza/concourse-poc.git
      branch: main
      file: ver
      initial_version: 0.0.1
      username: ((mlizza/username))
      password: ((mlizza/password))

jobs:
  - name: concourse-poc-job
    plan:
      # Add a get step referencing the resource
      - get: repo
        trigger: true   # tell Concourse to trigger this job when new versions are emitted
      - get: go-builder
      - get: version-bumper
        params: { pre: build }
#      - load_var: version
#        file: repo/VERSION
      - task: concourse-poc-task-printenv
        image: go-builder
        config:
          platform: linux
          run:
            path: sh
            args:
              - -cx
              - |
                printenv | sort
      - task: concourse-poc-task-version
        image: go-builder
        params:
          VERSION: ((.:version))
        file: repo/ci/tasks/go-version.yml
      - task: concourse-poc-task-build
        image: go-builder
        params:
          VERSION: ((.:version))
        file: repo/ci/tasks/go-build.yml
      - task: concourse-poc-task-test
        image: go-builder
        params:
          VERSION: ((.:version))
        file: repo/ci/tasks/go-test.yml
      - task: concourse-poc-task-coverage
        image: go-builder
        params:
          VERSION: ((.:version))
        file: repo/ci/tasks/go-coverage.yml
      - put: version-bumper
        params:
          file: ver
          bump: minor
#      - put: repo
#        params:
#          tag: repo/VERSION
#          tag_prefix: v
#          repository: repo
#          branch: main
